# .github/workflows/chromatic.yml

# Название процесса
name: "chromatic"

# Событие для процесса
on: push

# Список действий
jobs:
  sb-deployment:

    # ОС
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm i

      - name: Publish to Chromatic
        run: chromatic --project-token=59b7949a76b9 --build-script-name=storybook-build
        uses: chromaui/action@v1

        # Опции
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
