name: github-pages

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - "main"

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: LumbagoG/github-actions-react-to-ghp@v1.2.0
        with:
          path: storybook-static
          build_command: npm run storybook-build && rm -rf node_modules/.cache/gh-pages
