# Публикация в github-pages
name: "github-pages"

# Process event
on:
    pull_request:
        types: [ opened, reopened, edited, synchronize ]
        branches:
            - "master"
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

# List tasks
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run storybook-build && rm -rf node_modules/.cache/gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: storybook-static
