# Publish to npm repository
name: "publish-package-npm"

# Process event
on:
    pull_request:
        types: [ opened, reopened, edited, synchronize ]
        branches:
            - "develop"
    workflow_run:
        workflows: [ "publish-package-github" ]
        types:
            - completed
    release:
        types: [created]

# List tasks
jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
                    registry-url: https://registry.npmjs.org/
            -   run: npm ci
            -   run: npm publish
                env:
                    NODE_AUTH_TOKEN: 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
