# Публикация пакета в github packages
name: "publish-package-github"

# Событие для процесса
on:
    workflow_run:
        workflows: [ "chromatic" ]
        types:
            - completed
    pull_request:
        types: [ opened, reopened, edited, synchronize ]
        branches:
            - "develop"
    release:
        types: [published]

# Список действий
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            id-token: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@LumbagoG'
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
