# Релиз пакета
name: "release-package"

# Событие для процесса
on:
  workflow_run:
    workflows: ["build-bump-and-tag"]
    types:
      - completed

# Список действий
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_GITHUB}}
